language: python
before_install:
  - wget -O tests/consul_1.6.1_linux_amd64.zip https://releases.hashicorp.com/consul/1.6.1/consul_1.6.1_linux_amd64.zip
  - cd tests
  - unzip consul_1.6.1_linux_amd64.zip
  - mv consul consul.linux64
git:
  lfs_skip_smudge: true
matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: linux
          python: 3.7
          env: TOXENV=py37
        - os: linux
          python: pypy
          env: TOXENV=pypy
        - os: linux
          python: pypy3
          env: TOXENV=pypy3

install:
  - pip install tox
  - pip install tox-travis
script: tox