language: python

matrix:
    include:
        - os: linux
          python: 2,7
          env: TOXENV=py32
        - os: linux
          python: 3.3
          env: TOXENV=py33
        - os: osx
          language: generic
          env: TOXENV=py32
        - os: osx
          language: generic
          env: TOXENV=py33
install:
  - pip install tox
  - pip install tox-travis
script: tox