language: python
matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: linux
          python: 3.7
          env: TOXENV=py37
        - os: linux
          python: pypy
          env: TOXENV=pypy
        - os: linux
          python: pypy3
          env: TOXENV=pypy3

install:
  - pip install tox
  - pip install tox-travis
script: tox