language: python
python:
- 2.7
- pypy
- 3.5
- 3.6
- 3.7
install:
- pip install tox
- pip install tox-travis
script:
- tox
jobs:
  include:
  - stage: flake
    python: 3.7
    script:
    - tox -e flake8
  - stage: sonar
    dist: trusty
    language: python
    addons:
      sonarcloud:
        organization: python-consul2
        token:
          secure: ph5YrfxHBRp1wvMwZ4S63ADE8dNhTHiaHv1ur7GSq8ZxPEKM+inrt1P9Mv+iA0NP84SpDfm+/PSL96OLlxz0RonvLJM6F6CXz2CPapuNhsDqQ/fmaWtQ6ejfaqp48j8Us/IxSLeFVqUei+akQLSwlC4eHwF07OJaRMx2hqBsU+vfWJ9tfnD6Uu53iwjMlIo4k4f3bfhXULbR8BwO3YeDOcNWnWG+it7skICbvrlY/Fs3/bKHtn0SAuVEDaY8+I1bdrmW9eeFguPMvanN3w9QER06a+wWtmNwdrs0WGw8TIt5zwEKWwzMHSYzj5bE3ps9vbJ5Qh12iJqoBlx8g3vQePv35deDyy7kHqSOeYkY/5EygLuO9vn/X9jekqgL5s3rLCkQxiaE/lAhn5g8iQYWokeNjQNWQQ2G0ojkeXM1gYHQdEOwnYFDnPi9hpeCqAgu1ZkrCe5M7bPA8Cn3S8yeaO+LqpLLn046zg65kcTcWyCYJxUl4tZT7C3wugMcr/fY8XDTzPc41sx14vmbPvP6Pp/bqBc9E9mBbxPzo5U0vE/Y1nNL0G5jprsBD95wP9UcjCOEo1YZtd3qbh1nGePxgq6j9RligOjjJSPIILcGNPwwAtSu7kr4ft5tpZ+LnFzPuWnRC8se7YVvoGCHicqu9CqtkZ/l348HQod3Swu2VxM=
        branches:
        - master
    install: ignore
    script:
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi
    branches:
      only:
      - master
  - stage: deploy
    python: 3.7
    script: ignore
    deploy:
      provider: pypi
      user: python-consul-admin
      password:
        secure: HmLBvgjd5WB8nNBI/KbgvVPKUy1Wsb4TwLL2aEA4IrZHW0/8JHbwwo71zEX+ep+CvqCRTZDMfXtWbckpAJUhjGuqeFqiQGzxwU+SffJsdqy4mVl8NSUJ3WkWItYhPAhnbPYLTOg3QPAEY8KW0RrW1WW3X4wpwEe1+F+o3BDIvvw=
      distributions: sdist bdist_wheel
      on:
        tags: true
env:
  global:
    secure: qCG3f8HMxblYOBlkGNDs0wJKxLRCsk3YmAa2YHLn05T244AXjfJoI4MC6YbzlyyRXGch/V24mGk99dF0o+r6WIU2nYPWczL+IZ1raJMGLZUkWziyXVt8/wn+M31JyinwHIqxYcUEKJ6lcJTRGBbAclTRlzf6m2MAfttohiNiD/FBhh103rdjfFfktC1r0FEagFM3ynlC9i0JMkOchVfTb2kXIzzrmkY+uLj7K5iFl8hzPJ/qUnw71N1XSh5BCpsTU6T659bRLrCYrqQYGOv7hTlCrHzyz717A1EpISMmH+yZLGONeVxt6F1y/H5MjFyxd5ZWji3wIcRJj5TSeddXlaPb0y7fda9VfAwA1z0oScZBCFOEV5dtNxQAfyi9LvBcnAZsXQlvwzZVg93x7pz5p2AKGm2euhJWThz6I1lqbQFxjCuR5JWlDZNxCyx6jyij7c29LpCSbkQ+9UUNXqBufi817TlfSorRdEf6dLqz9p5O2hlBvGIGFXztdtJ6AdWjQmE9X1kgaQwSp/6/GwazmObDkbesm7BryipAeiSFGu2fuphA8E8X4jCSmAcewdorpkPI9CEApw4Nz9sx/lToh7jR8vLDSeC7aJ/VWUuaeLyhANhzEVQV/6WNI6JuWpC92OhNw6db4ARODhtmHnDqh9f6QA9z/cyZbB3Pu4M0HZE=
